### ISSUE TITLE
.drone.yml example

### ISSUE THREAD

**Issue by devth** [jmccann/drone-github-comment#1]
Awesome plugin. Could you show a sample of .drone.yml usage in the README? Not clear to me if the api key needs to be specified there since Drone already has access to GitHub out of necessity.

**Comment by jmccann** [comment]
I did play with the token drone already has via the `NETRC_PASSWORD` but couldn't get it to work (http 401 auth error).  I may try more later as I may have been doing something wrong.

For now you will need to create/use a token.

And yes, docs/examples for this would be good.  I'll try to get to that soon.

**Comment by jmccann** [comment]
```
pipeline:
  comment:
    image: jmccann/drone-github-comment:1
    secrets: [ github_token ]
    message: "Hello World"
```
