### ISSUE TITLE
Ability to run custom commands with the default drone credentials

### ISSUE THREAD

**Issue by salimane** [jmccann/drone-github-comment#2]
The following pipeline block works:
```
droneGithubComment:
    image: jmccann/drone-github-comment:1.2
    message_file: hello.file
```
I am guessing it's using the default drone credentials.

Now if I modify the pipeline block to run custom commands, I get an error:

```
droneGithubComment:
    image: jmccann/drone-github-comment:1.2
    entrypoint: ''
    commands:
      - /bin/drone-github-comment --message-file=hello.file
```

```shell
+ /bin/drone-github-comment --message-file=hello.file
time="2018-11-23T09:23:29Z" level=info msg="Drone Github Comment Plugin Version" Revision= 
time="2018-11-23T09:23:29Z" level=fatal msg="You must provide an API key or Username and Password" 
```
After supplying the ``github_token`` secret , I am now getting

```
+ /bin/drone-github-comment --message-file=hello.file
time="2018-11-23T13:22:20Z" level=info msg="Drone Github Comment Plugin Version" Revision= 
time="2018-11-23T13:22:20Z" level=fatal msg="POST https://api.github.com/repos/salimane/my-repo/issues/109/comments: 404 Not Found []" 
```

@jmccann do you have an idea what's happening here?
